name: Test TensorFlow
on: push

defaults:
  run:
    shell: bash -l {0}

jobs:

  install-with-gpu:
    name: Install TensorFlow with GPU support
    runs-on: macos-14
    steps:

      - name: Install Miniconda
        run: |
          mkdir -p ~/miniconda3
          curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh -o ~/miniconda3/miniconda.sh
          bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
          rm -rf ~/miniconda3/miniconda.sh

      - name: Create and populate Conda env
        run: |
          conda create -n tensorflow-py311 --yes -c conda-forge python=3.11
          conda activate tensorflow-py311
          which python
          python -m pip install tensorflow==2.13
          python -m pip install tensorflow-metal

      - name: Check TensorFlow devices
        run: |
          conda activate tensorflow-py311
          python -c '
          import tensorflow as tf
          print("Devices detected: ", tf.config.list_physical_devices())
          '
